version: '3.6'

services:
  nodered:
    image: ctmagazin/ctnodered:latest
    ports:
      - "1880:1880"
    volumes:
      - ./data/nodered:/data
      - /etc/localtime:/etc/localtime
    depends_on:
      - mqtt
    restart: always
    #inetwork_mode: "host"
    environment:
      - TZ=Europe/Berlin
    hostname: nodered
    
  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./data/mqtt:/mosquitto
      - /etc/localtime:/etc/localtime
    restart: always
    environment:
      - TZ=Europe/Berlin
    hostname: mqtt
    
  zigbee:
    image: koenkk/zigbee2mqtt
    volumes:
      - ./data/zigbee:/app/data
      - /run/udev:/run/udev:ro
      - /etc/localtime:/etc/localtime
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyACM1:/dev/ttyACM1"
    restart: always
    privileged: true
    environment:
      - TZ=Europe/Berlin

  zigbeeadmin:
    image: carldebilly/zigbee2mqttassistant
    environment:
      - Z2MA_SETTINGS__MQTTSERVER=mqtt
      - TZ=Europe/Berlin
    ports:
      - 8880:80
    restart: always
  
  homeassistant:
    image: homeassistant/home-assistant
    volumes:
      - ./data/homeassistant:/config
      - /etc/localtime:/etc/localtime
    restart: always
    privileged: true
    environment:
      - TZ=Europe/Berlin
    ports:
      - 8123:8123
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyACM1:/dev/ttyACM1"
    hostname: homeassistant

  tasmoadmin:
    image: raymondmm/tasmoadmin
    volumes:
      - ./data/tasmoadmin:/data
      - /etc/localtime:/etc/localtime
    restart: always
    privileged: true
    environment:
      - TZ=Europe/Berlin
    ports:
        - 8881:80
    hostname: tasmoadmin

  grafana:
    image: grafana/grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - TZ=Europe/Berlin
    restart: always
    privileged: true
    user: "1000"
    hostname: grafana

  influxdb:
    image: influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb
      - /etc/localtime:/etc/localtime
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_DB=data
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - TZ=Europe/Berlin
    restart: always
    privileged: true
    hostname: influxdb

  chronograf:
    image: chronograf
    volumes:
      - ./data/chronograf:/var/lib/chronograf
      - /etc/localtime:/etc/localtime
    ports:
      - 8888:8888
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - TZ=Europe/Berlin
    restart: always
    privileged: true
    hostname: chronograf
